language: ruby
cache: bundler
script:
  - bundle exec jekyll build --incremental

install:
  - gem install jekyll
  - gem install jekyll-sitemap
  - gem install jekyll-paginate


deploy:
  provider: pages
  local-dir: ./_site
  target-branch: master
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  on:
    branch: master