title: DataBytes Podcast
description: 
author: 
about: Freelance developer

baseurl: "https://databytespodcast.github.io"
url: "https://databytespodcast.github.io"

allowsearch: true

google_analytics: 

share:
  twitter_username: \#
  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
