title: DataBytes Podcast
description: 
author: 

baseurl: "https://databytespodcast.github.io"
url: "https://databytespodcast.github.io"

allowsearch: false

google_analytics: UA-130201304-1

share:
  twitter_username: 
  fb_appid: 

disqus_shortname: "databytes-podcast"

enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
